# Generated by Django 3.1.4 on 2021-04-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.RemoveField(
            model_name='service',
            name='release_date',
        ),
        migrations.AddField(
            model_name='service',
            name='service_number',
            field=models.IntegerField(default=100, verbose_name='Номер отображения'),
        ),
    ]
