# Generated by Django 3.1.4 on 2021-05-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsite', '0002_auto_20210430_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_is_active',
            field=models.BooleanField(default=True, verbose_name='Видимость для покупки'),
        ),
    ]
