# Generated by Django 3.1.4 on 2021-05-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsite', '0003_service_service_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_photo',
            field=models.ImageField(upload_to='images', verbose_name='Фотография услуги'),
        ),
    ]
