# Generated by Django 3.1.4 on 2021-05-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsite', '0004_auto_20210506_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_photo',
            field=models.ImageField(upload_to='natal/newsite/templates/newsite/images', verbose_name='Фотография услуги'),
        ),
    ]
