# Generated by Django 3.1.4 on 2021-06-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsite', '0007_auto_20210621_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default='2000-01-01', verbose_name='Дата и время заказа'),
        ),
    ]
